begin;
insert into public.profiles(id) values('00000000-0000-4000-8000-000000000110'),('00000000-0000-4000-8000-000000000111');
insert into public.admin_users(user_id,role) values('00000000-0000-4000-8000-000000000001','owner'),('00000000-0000-4000-8000-000000000002','support');
do $$
declare u uuid:='00000000-0000-4000-8000-000000000110'; other_user uuid:='00000000-0000-4000-8000-000000000111';
  actor uuid:='00000000-0000-4000-8000-000000000001'; supporter uuid:='00000000-0000-4000-8000-000000000002';
  request_id uuid:=gen_random_uuid(); intent uuid; transaction_id uuid; old_transaction uuid; wrong_transaction uuid; result jsonb; balance_before integer;
begin
  perform public.test_assert(public.get_native_checkout_support(actor,u) is null,'support flag defaults off');
  begin perform public.get_native_checkout_support(u,u);raise exception 'non-admin read accepted';exception when sqlstate '42501' then null;end;
  update private.native_commerce_settings set checkout_protection_enabled=true,customer_compatibility_enabled=true,acquisition_enabled=true;
  insert into public.native_product_availability(product_version_id,available) select id,true from public.native_product_versions on conflict(product_version_id) do update set available=true;
  perform public.test_assert(public.recover_native_purchase_selection(u,'SANDBOX','APP_STORE',request_id)->>'status'='not_found','missing selection is explicitly absent');
  begin perform public.recover_native_purchase_selection(u,'PRODUCTION','APP_STORE',request_id);raise exception 'cross-env recovery';exception when sqlstate '55000' then null;end;
  begin perform public.recover_native_purchase_selection(u,'SANDBOX','STRIPE',request_id);raise exception 'Stripe recovery via native';exception when sqlstate '22023' then null;end;
  intent:=(public.begin_customer_purchase_intent(u,'SANDBOX','APP_STORE','pack20',request_id,repeat('a',64))->>'intentId')::uuid;
  perform public.test_assert(public.recover_native_purchase_selection(other_user,'SANDBOX','APP_STORE',request_id)->>'status'='not_found','request ID is not cross-account authority');
  update private.native_commerce_settings set acquisition_enabled=false;
  perform public.test_assert(public.recover_native_purchase_selection(u,'SANDBOX','APP_STORE',request_id)->>'status'='cancelled','cancel unstarted selection while acquisition off');
  perform public.test_assert(public.recover_native_purchase_selection(u,'SANDBOX','APP_STORE',request_id)->>'status'='cancelled','cancel selection idempotent');
  update private.native_commerce_settings set acquisition_enabled=true;
  old_transaction:=(public.record_verified_native_purchase(u,'SANDBOX','APP_STORE','support-old','support-old','pack20',clock_timestamp()-interval '1 day')->>'transactionId')::uuid;
  wrong_transaction:=(public.record_verified_native_purchase(other_user,'SANDBOX','APP_STORE','support-other','support-other','pack20',clock_timestamp())->>'transactionId')::uuid;
  request_id:=gen_random_uuid();
  intent:=(public.begin_customer_purchase_intent(u,'SANDBOX','APP_STORE','pack20',request_id,repeat('a',64))->>'intentId')::uuid;
  perform public.launch_customer_purchase_intent(u,'SANDBOX',intent,'APP_STORE');
  perform public.test_assert(public.recover_native_purchase_selection(u,'SANDBOX','APP_STORE',request_id)->>'status'='pending','recovery cannot clear launched checkout');
  result:=public.get_native_checkout_support(supporter,u);
  perform public.test_assert(jsonb_array_length(result->'intents')=1 and result#>'{intents,0,candidates}'='[]'::jsonb,'support sees pending checkout but no stale or other-account candidates');
  begin perform public.link_verified_native_checkout(supporter,u,intent,old_transaction,'Support cannot change purchases');raise exception 'support wrote';exception when sqlstate '42501' then null;end;
  begin perform public.link_verified_native_checkout(actor,u,intent,old_transaction,'Old receipt must not unlock checkout');raise exception 'old txn linked';exception when sqlstate '42501' then null;end;
  begin perform public.link_verified_native_checkout(actor,u,intent,wrong_transaction,'Cross account must be denied');raise exception 'wrong user txn linked';exception when sqlstate '42501' then null;end;
  transaction_id:=(public.record_verified_native_purchase(u,'SANDBOX','APP_STORE','support-real','support-real','pack20',clock_timestamp())->>'transactionId')::uuid;
  result:=public.get_native_checkout_support(actor,u);
  perform public.test_assert(result#>>'{intents,0,candidates,0,id}'=transaction_id::text,'only exact eligible verified transaction shown');
  perform public.test_assert(result::text not like '%support-real%' and result::text not like '%store_transaction_id%','support response excludes external receipt identifiers');
  begin perform public.link_verified_native_checkout(actor,u,intent,transaction_id,'short');raise exception 'short reason';exception when sqlstate '22023' then null;end;
  balance_before:=public.credit_balance(u);
  result:=public.link_verified_native_checkout(actor,u,intent,transaction_id,'Matched the verified payment for interrupted checkout');
  perform public.test_assert(result->>'status'='verified','verified payment settles checkout');
  perform public.test_assert(public.credit_balance(u)=balance_before,'support link never grants or debits credits');
  perform public.link_verified_native_checkout(actor,u,intent,transaction_id,'Retry after interrupted response');
  perform public.test_assert((select count(*)=1 from private.native_checkout_support_audit where intent_id=intent),'replay preserves single original audit');
  perform public.test_assert(public.read_native_purchase_intent(u,'SANDBOX',intent)->>'status'='verified','app can observe Admin resolution');
  perform public.test_assert(public.get_native_checkout_support(actor,u)->'intents'='[]'::jsonb,'resolved checkout no longer actionable');
  update public.admin_users set is_active=false where user_id=actor;
  begin perform public.link_verified_native_checkout(actor,u,intent,transaction_id,'Disabled administrator must be denied');raise exception 'inactive admin linked';exception when sqlstate '42501' then null;end;
  perform public.test_assert(not has_function_privilege('authenticated','public.link_verified_native_checkout(uuid,uuid,uuid,uuid,text)','EXECUTE'),'customer cannot forge Admin actor');
  perform public.test_assert(not has_table_privilege('service_role','private.native_checkout_support_audit','DELETE'),'service cannot delete audit');
end; $$;
rollback;
